language: go
sudo: required
dist: trusty

go:
  - "1.10.x"

services:
  - redis-server
  - postgresql

addons:
  postgresql: "9.5"

env:
  - TEST_POSTGRES_DSN=postgres://postgres@localhost/loraserver?sslmode=disable

before_install:
  - sudo apt-add-repository -y ppa:mosquitto-dev/mosquitto-ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y mosquitto
  - make requirements

before_script:
  - psql -c 'create database loraserver;' -U postgres

script:
  - make test

before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;

      make dist;

      rvm --default use system;
      sudo apt-get install -y ruby ruby-dev;
      sudo gem install --no-ri --no-rdoc fpm;

      PACKAGE_ARCH=x86_64 make package-deb;
      PACKAGE_ARCH=i386 make package-deb;
      PACKAGE_ARCH=armhf make package-deb;
      PACKAGE_ARCH=arm64 make package-deb;

      mkdir -p dist/upload/tar;
      mkdir -p dist/upload/deb;
      mv dist/*.tar.gz dist/upload/tar;
      mv dist/deb/*.deb dist/upload/deb;
    fi

deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAJLTNEMD6RLNMP2NQ
    secret_access_key:
      secure: pnQNOFBYjOJ05WtwQxKHT/Wlgnefgox8OjaTL7xU7pDafDxlP24IKcCA9D7rg6ofWoX/OEcbtfFgJJOGRGCOheB3jji/HKlfVQJwANCJyF2mViveHSBniLPS7SlQ4YXiH1+bS0d+iPMzCiGVkBnH1v6ezzr7TDsb6436hHVI7FJZzJXy+QXX8A04pxXRtl9KJySlVR4hpcMQdY8mADFmmQ8LXjCMlIOBVjj00YCVMoZoE0WCQSmA0UB2LaMF1k0256FjPiIVJKXXh6TZmGmBpgt89D9IAQWjumgZZptGKoOBCfaLQdoS+hXsJmx3AgDWzqyx+tYiz/EXu6sjSWWDNIpvBhkHTPkTqDQqKUevL8WYdvrp42wk1/OxeqBpwh5SMA3uST6smqJ+EUS/8hmCVKQyfzvqf/hSYxARm5Qpa1yvEGwHnqXA3KoqZl8DMTivggmP/uN73kocZXwZeI7Dv8bIhSgQ+yHDgBCVR8UGhXtUp78aUIANxndVXvyJQKy9ThVCXJwtZCbAD5w88xt9LMAfnVmPQcf+i4aDWGDNR51VwysnGeixOUvLFPtD0EWx9W1lFtwQtK1hjXnm6SPkJ3CudMPjjpI/6QrHdv6lHMAd8qPlAEiz/OhdZxDkpENYUXk07mzJMB73K5+GMZqtuPCRBH1xJYg7m7IILT3QtPE=
    bucket: builds.loraserver.io
    local-dir: dist/upload
    upload-dir: loraserver
    acl: private
    region: eu-west-1
    on:
      tags: true
      repo: brocaar/loraserver
